### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [diegoos/cleanzsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by diegoos** [comment]
Hello @unixorn.

I'll take a look at this later.
I'll update the repository and add a license. :)

Thanks!

**Comment by diegoos** [comment]
Hi @unixorn.

I was busy last week. 
I finally add a License and update the code.

**Comment by unixorn** [comment]
Thanks, adding it.
